name: Apply service configuration to Kong gateway

on:
  push:
    branches:
      - master

jobs:
  deploy_to_kong:
    runs-on: self-hosted
    name: Apply service configuration to Kong gateway
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ping Kong
        run: deck ping --kong-addr ${{ vars.GATEWAY_HOST }} --headers kong-admin-token: ${{ secrets.EC2_KONG_TOKEN_SB }}
      - name: Check service config differences
        run: deck diff --kong-addr ${{ vars.GATEWAY_HOST }} --headers kong-admin-token: ${{ secrets.EC2_KONG_TOKEN_SB }} -s 
